import type { EnvironmentProfile } from "../rendering/profile";
import { BONNEVILLE_SUN_DIRECTION } from "../bonneville-light";
export const nightYard: EnvironmentProfile = {
  background: 0x07101c,
  fogDensity: 0.0065,
  lowFogDensity: 0.009,
  skyColor: 0x9cc8ff,
  groundColor: 0x151c14,
  ambientIntensity: 1.65,
  sunColor: 0xffe0bb,
  sunIntensity: 3.2,
  sunOffset: [-24, 38, -18],
  exposure: 1.05,
  near: 0.08,
  far: 620,
  cameraRadius: 20,
  adaptiveNear: false,
  cityHorizon: true,
  bodyClass: "",
  cruise: false,
};
export const saltMorning: EnvironmentProfile = {
  background: 0xd1c7bd,
  fogDensity: 0.000018,
  lowFogDensity: 0.000018,
  skyColor: 0xa5c1e0,
  groundColor: 0x9e9690,
  ambientIntensity: 1.5,
  sunColor: 0xffd2a0,
  sunIntensity: 3,
  sunOffset: [
    BONNEVILLE_SUN_DIRECTION.x * 60,
    BONNEVILLE_SUN_DIRECTION.y * 60,
    BONNEVILLE_SUN_DIRECTION.z * 60,
  ],
  exposure: 0.9,
  near: 0.2,
  far: 80000,
  cameraRadius: 1200,
  adaptiveNear: true,
  cityHorizon: false,
  bodyClass: "salt-world",
  cruise: true,
};
